services:
  test:
    image: "exercise-3"
    volumes:
      - .:/app
    command: python3 -m pytest
  run:
    environment:
      - AWS_PROFILE=default
    image: "exercise-3"
    volumes:
      - ~/.aws:/root/.aws:ro
      - .:/app
    command: python3 main.py
